libcmis: Autospec creation for update from version 0.5.1 to version 0.5.2
Andreas Müller (1):
      Fix build with boost >= 1.68.0

David Tardon (67):
      produce xz-compressed tarballs
      bump revision for the next release
      add gdrive fix to NEWS
      and -> &&
      update boost.m4 to fix version detection with gcc 6.1
      rhbz#1410197 limit the number of redirections
      limit the number of redirections for PUT too
      IMHO 100 redirections is overkill
      drop :: prefix
      do not reinvent the wheel
      fix build error with gcc -std=c++98
      do not try to use [] on an empty string
      return early if the time part is empty
      WaE: catch exception by ref
      nothing to see here, move along
      simplify this
      WaE (C++14): also define sized delete
      move API headers into a separate dir
      move conditional up
      use tabs for indentation
      sort various file lists lexicographically
      generate versioned .pc files from configure
      do not override compiler opt. flags
      include API headers with full path
      include API headers with full path
      ensure headers are self-containing
      cppcheck: disable information messages
      allow to use cppcheck in out-of-tree build
      speed up cppcheck runs
      fold checks for docbook2man variants into one
      save some vertical space
      move cppcheck to a separate target
      simplify a bit
      use unique_ptr
      do not reinvent the wheel
      make the intent more clear
      apply the standard ordering of headers
      make the intent more clear
      make the intent more clear
      only export public API symbols
      only ignore autogenerated files in m4
      drop obsolete file from tarball
      use automake support for man pages
      be more consistent with naming conditionals
      fix comment in C header
      move common test files to a helper library
      fix copypasta
      use of libcurl is impl. detail
      nitpick
      add bug reporting section to man page
      update man page revision date
      fill in package version in man page automatically
      reformat man page
      reformat man page using more force
      replace boost::scoped_ptr by std::unique_ptr
      replace BOOST_FOREACH by foreach loop
      curl-mockup: fix long-standing leak in tests
      mockup-config: fix another hidden leak in tests
      session-factory: match comment to reality
      http-session: use unique_ptr to manage memory
      oauth2-providers: fix leak
      oauth2-providers: drop intermediate var
      fix condition
      make accessors const
      cid#328430 pass object by const ref
      shorten the code a bit
      update NEWS

Giuseppe Castagno (5):
      Add new Google Drive OAuth 2.0 login procedure.
      Add new mokup login pages
      Fix test in test-factory
      Fix test in test-gdrive
      Fix test in test-onedrive

Mike Kaganski (1):
      tdf#101385: don't try to get SharePoint folder outside of allowed range

Miklos Vajna (2):
      Switch to C++11
      Remove dynamic exception specifications

Szymon Kłos (7):
      google 2FA implementation
      gdrive 2FA test
      gdrive: test, new challenge page
      google 2FA fix, new challenge page
      removed unnecessary conditions
      macros with string literals and length
      Fix 2FA for Google Drive

Thorsten Behrens (4):
      Update AUTHORS
      Test corner-cases for parseDateTime
      Catch empty / incomplete datetime strings early
      -wError C4101: 'e' : unreferenced local variable

Tomas Chvatal (1):
      libcmis is not a GNU-conformant project

stbergmann (1):
      Properly encode OAuth2 credentials (#25)